version: '3.8'

services:
  www:
    build: .
    container_name: php_web
    image: php:8.2-apache
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 'ileana'
      DB_NAME: eventos
      DB_PORT: 3306
    networks:
      - app-network

  db:
    image: mariadb:11.1.2
    container_name: mariadb_db
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: eventos
      MYSQL_USER: 'ileana'
      MYSQL_PASSWORD: 'ile'
      MYSQL_ROOT_PASSWORD: 'ile'
    volumes:      
      - ./database:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin_gui
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      MYSQL_USER: 'ileana'
      MYSQL_PASSWORD: 'ile'
      MYSQL_ROOT_PASSWORD: 'ile'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
